Refactor GitHub Actions to ensure jobs always run
Modified workflow logic to always execute build and test jobs. Added checks to conditionally skip execution when no relevant changes are detected.

Signed-off-by: Gustavo Lira <guga.java@gmail.com>

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -66,7 +66,7 @@ jobs:
     name: Build with Node.js ${{ matrix.node-version }}
     runs-on: ubuntu-latest
     needs: check-image
-    if: ${{ needs.check-image.outputs.relevant_changes == 'true' || needs.check-image.outputs.image_exists == 'false' }}
+    if: always()
     strategy:
       matrix:
         node-version: [22]
@@ -75,6 +75,13 @@ jobs:
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
         with:
           fetch-depth: 0
+
+      - name: Check if build should be skipped
+        run: |
+          if [[ "${{ needs.check-image.outputs.relevant_changes }}" == "false" && "${{ needs.check-image.outputs.image_exists }}" == "true" ]]; then
+            echo "Skipping build: Image already exists and no relevant changes detected."
+            exit 0
+          fi
 
       - name: Setup Node.js
         uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
@@ -100,7 +107,7 @@ jobs:
     name: Test with Node.js ${{ matrix.node-version }}
     runs-on: ubuntu-latest
     needs: check-image
-    if: ${{ needs.check-image.outputs.relevant_changes == 'true' || needs.check-image.outputs.image_exists == 'false' }}
+    if: always()  # Sempre executa o job
     strategy:
       matrix:
         node-version: [22]
@@ -110,8 +117,15 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Check if tests should be skipped
+        run: |
+          if [[ "${{ needs.check-image.outputs.relevant_changes }}" == "false" && "${{ needs.check-image.outputs.image_exists }}" == "true" ]]; then
+            echo "Skipping tests: No relevant changes detected."
+            exit 0
+          fi
+
       - name: Setup Node.js
-        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
+        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
         with:
           node-version: ${{ matrix.node-version }}
           registry-url: 'https://registry.npmjs.org'
@@ -132,8 +146,8 @@ jobs:
 
       - name: Regenerate dockerfiles
         run: |
-          yarn run build:dockerfile; if [[ $(git diff --name-only | grep Dockerfile || true) != "" ]]; then \
-            echo "ERROR: Workspace is dirty! Must run 'yarn build:dockerfile' and commit changes!"; exit 1; \
+          yarn run build:dockerfile; if [[ $(git diff --name-only | grep Dockerfile || true) != "" ]]; then
+            echo "ERROR: Workspace is dirty! Must run 'yarn build:dockerfile' and commit changes!"; exit 1;
           fi
 
       - name: Run tests
